### ISSUE TITLE
FedData not fetching data using get_nlcd() 

### ISSUE THREAD

**Issue by msleckman** [msleckman/chart-challenge-22#3]
I am trying to run `get_nlcd()` function from the FedData Package. Getting an error when running. 

See code : 
```
library(FedData)
library(sf)
library(stringr)
library(dplyr)

## Already a target
shp_zip <- sbtools::item_file_download(sb_id = '5d94949de4b0c4f70d0db64f',
                                names = 'physiographic_regions_DRB.zip',
                                destinations = '1_fetch/out/physiographic_regions_DRB.zip',
                                overwrite_file = TRUE)

shp_unzip <- unzip(DRB_boundary_zip, exdir = '1_fetch/out/physiographic_regions_DRB', overwrite = TRUE)

drb_boundary <- st_read(drb_boundary_unzip %>% str_subset('.shp$')) %>%
      group_by(Source) %>%
      summarize() %>% 
      mutate(region = 'drb')

## Getting error
> library(FedData)
> get_nlcd(drb_boundary, 'drb',
+          year = 2019,
+          dataset = "landcover",
+          raw.dir = "1_fetch/out/RAW/NLCD")


Area of interest includes 6 NLCD tile(s).
(Down)Loading NLCD tile: N36W072
Downloading file: https://prd-tnm.s3.amazonaws.com/StagedProducts/NLCD/data/2019/landcover/3x3/NLCD2019_LC_N36W072.zip
Error in value[[3L]](cond) : 
  nlcd file /Users/msleckman/USGS/Vizlab/chart-challenge-22/23_tiles_msleckman/1_fetch/out/RAW/NLCD/NLCD2019_LC_N36W072.zip corrupt or incomplete. Please delete the file and try again.
In addition: Warning messages:
1: In if (class(x) != "extent") { :
  the condition has length > 1 and only the first element will be used
2: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings


```

there is a in dev version of the FedData package as well as a CRAN version. See repo [readme.md](https://github.com/ropensci/FedData)
I attempted to load `devtools::install_github("ropensci/FedData")` but could not install successfully.

**Comment by hcorson-dosch-usgs** [comment]
So -- according to [this issue](https://github.com/ropensci/FedData/issues/62) , looks like NLCD file services have changed but the FedData README.md examples haven't been updated. Per the recommendation in that issue, I installed the latest development version with ​​`devtools::install_github("ropensci/FedData")​​`. Once I'd done so your code snippet worked, so long as I removed the `raw.dir` argument so that the call to `get_nlcd()` looked like this:

```
get_nlcd(drb_boundary, 'drb',year = 2019,dataset = "landcover")
```
At first glance the raster looks right:
![image](https://user-images.githubusercontent.com/54007288/163488418-bc61ddfa-1885-4a03-8daf-1edd54bf736f.png)
